<div class='festi-sale-price-block' data-error='<?php echo __( 'Please enter in a value less than the '.$name.' price.', 'woocommerce' ); ?>'>
<?php
   $args['description'] = '<a href="#" class="festi-sale-role-schedule">'.
                        __('Schedule', $this->_languageDomain).'</a>';
   woocommerce_wp_text_input($args);
   
   $hideField = 'festi-hide-fields';
    
   if ($saleRolePriceDatesFrom || $saleRolePriceDatesTo) {
       $hideField = '';
   }
?>
    <p class="form-field festi-sale-price-dates-fields <?php echo $hideField; ?>">
        <label for="_sale_price_dates_from_<?php echo $name; ?>">
             <?php __($name.' Sale Price Dates',  $this->_languageDomain); ?></label>
        <input type="text" 
            class="short festi-sale-price-date-from"
            name="<?php echo PRICE_BY_ROLE_PRICE_META_KEY; ?>[schedule][<?php echo $name;?>][date_from]"
            id="_sale_price_dates_from_<?php echo $name; ?>"
            value="<?php echo $saleRolePriceDatesFrom; ?>" 
            placeholder="<?php echo _x('From&hellip;', 'placeholder',  $this->_languageDomain); ?> YYYY-MM-DD"
            maxlength="10"
            pattern="[0-9]{4}-(0[1-9]|1[012])-(0[1-9]|1[0-9]|2[0-9]|3[01])" />
        <input type="text" class="short"
            name="<?php echo PRICE_BY_ROLE_PRICE_META_KEY; ?>[schedule][<?php echo $name;?>][date_to]"
            id="_sale_price_dates_to_<?php echo $name; ?>"
            value="<?php echo $saleRolePriceDatesTo; ?>"
            placeholder="<?php echo _x('To&hellip;', 'placeholder', $this->_languageDomain); ?> YYYY-MM-DD"
            maxlength="10"
            pattern="[0-9]{4}-(0[1-9]|1[012])-(0[1-9]|1[0-9]|2[0-9]|3[01])" />
        
        <a href="#" class="festi-sale-price-schedule-cancel">
            <?php  echo __( 'Cancel', 'woocommerce' ); ?>
        </a>
        <img class="help_tip" style="margin-top: 21px;"
            data-tip="<?php 
            echo esc_attr__(
                'The sale will end at the beginning of the set date.',
                'woocommerce'
            ); ?>"
            src="<?php echo esc_url( WC()->plugin_url() ); ?>/assets/images/help.png"
            height="16"
            width="16" />
    </p>
</div>