<?php
    $id = PRICE_BY_ROLE_VARIATION_RICE_KEY.'_'.$loop.'_'.$keyRole;
    $nameSalePrice = PRICE_BY_ROLE_VARIATION_RICE_KEY.'['.$loop.'][salePrice]['.$keyRole.']';
    $nameRegularPrice = PRICE_BY_ROLE_VARIATION_RICE_KEY.'['.$loop.']['.$keyRole.']';
    $nameDateFrom = PRICE_BY_ROLE_VARIATION_RICE_KEY.'['.$loop.'][schedule]['.$keyRole.'][date_from]';
    $nameDateTo = PRICE_BY_ROLE_VARIATION_RICE_KEY.'['.$loop.'][schedule]['.$keyRole.'][date_to]';
    
    $hideField = 'festi-hide-fields';
    
   if ($datesRole['from'] || $datesRole['to']) {
       $hideField = '';
   }
?>
<div class="variable_pricing" data-error="<?php echo __( 'Please enter in a value less than the '.$role['name'].' price.', 'woocommerce' ); ?>">
    <p class="form-row form-row-first">
        <label>
            <?php echo $label; ?>
        </label>
        <input type="text" size="5" 
               name="<?php echo $nameRegularPrice;?>"
               value="<?php echo  $rolePrice; ?>"
               class="wc_input_price"
               placeholder="<?php esc_attr_e( 'Variation price (required)', 'woocommerce' ); ?>" />
    </p>
    <p class="form-row form-row-last">
        <label>
            <?php echo __($role['name'].' Sale Price: ', 'woocommerce') . ' (' . get_woocommerce_currency_symbol() . ')'; ?>
            <a href="#" class="sale_schedule"
                <?php if (!$hideField || $isDiscountEnabled) { ?>
                    style="display: none;"
                <?php }?>>
                <?php _e( 'Schedule', 'woocommerce' ); ?>
            </a>
            <a href="#" class="cancel_sale_schedule <?php echo $hideField; ?>">
                <?php _e( 'Cancel schedule', 'woocommerce' ); ?>
            </a>
        </label>
        <input type="text" size="5" 
               name="<?php echo $nameSalePrice; ?>"
               value="<?php echo $roleSalePrice; ?>"
               class="wc_input_price festi-role-sale-price"
               <?php if ($isDiscountEnabled) { ?>readonly<?php } ?> />
    </p>

    <div class="sale_price_dates_fields <?php echo $hideField; ?>">
        <p class="form-row form-row-first">
            <label>
                <?php _e( 'Sale start date:', 'woocommerce' ); ?>
            </label>
            <input type="text" class="sale_price_dates_from"
                   name="<?php echo $nameDateFrom; ?>"
                   value="<?php echo $datesRole['from']; ?>"
                   placeholder="<?php echo esc_attr_x( 'From&hellip;', 'placeholder', 'woocommerce' ) ?> YYYY-MM-DD"
                   maxlength="10"
                   pattern="[0-9]{4}-(0[1-9]|1[012])-(0[1-9]|1[0-9]|2[0-9]|3[01])" />
        </p>
        <p class="form-row form-row-last">
            <label>
                <?php _e( 'Sale end date:', 'woocommerce' ); ?>
            </label>
            <input type="text" class="sale_price_dates_to"
                   name="<?php echo $nameDateTo; ?>"
                   value="<?php echo $datesRole['to']; ?>"
                   placeholder="<?php echo esc_attr_x('To&hellip;', 'placeholder', 'woocommerce') ?> YYYY-MM-DD"
                   maxlength="10"
                   pattern="[0-9]{4}-(0[1-9]|1[012])-(0[1-9]|1[0-9]|2[0-9]|3[01])" />
        </p>
    </div>
</div>